"""init_db() must be able to build a database from nothing.

The 'initial schema' migration creates no tables — it was autogenerated as a
diff against a database SQLModel.metadata.create_all() had already built, so
it only contains alter_column operations. Running the chain against an empty
database therefore fails on the first revision.

For a fresh database the models are the source of truth: create the schema,
then stamp the migration chain as applied. An existing database still goes
through the normal upgrade path.
"""

import sqlite3

import pytest
from sqlalchemy import inspect

from src.storage.database import get_engine, init_db


@pytest.fixture
def fresh_url(tmp_path):
    return f"sqlite:///{tmp_path / 'fresh.db'}"


def _tables(url):
    return set(inspect(get_engine(url)).get_table_names())


def _head_revision():
    from alembic.config import Config
    from alembic.script import ScriptDirectory

    return ScriptDirectory.from_config(Config("alembic.ini")).get_current_head()


def test_builds_schema_on_empty_database(fresh_url):
    init_db(fresh_url)

    tables = _tables(fresh_url)
    for expected in ("articles", "users", "digests", "digest_clicks"):
        assert expected in tables, f"{expected} missing from fresh database"


def test_fresh_database_includes_latest_columns(fresh_url):
    """create_all() builds the current model state, verdict column included."""
    init_db(fresh_url)

    columns = {
        c["name"] for c in inspect(get_engine(fresh_url)).get_columns("articles")
    }
    assert "why_it_matters" in columns
    assert "section" in columns


def test_fresh_database_is_stamped_at_head(fresh_url):
    """Without a stamp, the next init_db() would replay migrations over a
    schema that already has those columns."""
    init_db(fresh_url)

    assert "alembic_version" in _tables(fresh_url)
    con = sqlite3.connect(fresh_url.replace("sqlite:///", ""))
    version = con.execute("select version_num from alembic_version").fetchone()[0]
    con.close()
    assert version == _head_revision()


def test_init_db_is_idempotent(fresh_url):
    init_db(fresh_url)
    init_db(fresh_url)  # must not raise on the already-migrated path

    assert "articles" in _tables(fresh_url)


def test_existing_database_keeps_its_data(fresh_url):
    """The upgrade path must never clobber an existing database."""
    init_db(fresh_url)
    path = fresh_url.replace("sqlite:///", "")

    con = sqlite3.connect(path)
    con.execute(
        "insert into users (email, name, password_hash, role, level, "
        "topics_json, source_preferences_json, is_admin, active, "
        "email_verified, session_version, created_at) "
        "values ('a@b.com','A','x','student','beginner','[]','{}',0,1,0,0,'2026-01-01')"
    )
    con.commit()
    con.close()

    init_db(fresh_url)

    con = sqlite3.connect(path)
    count = con.execute("select count(*) from users").fetchone()[0]
    con.close()
    assert count == 1
