import threading
from contextlib import contextmanager
from pathlib import Path

from sqlalchemy import inspect
from sqlmodel import Session, SQLModel, create_engine

from src.config import load_settings

_engine = None
_engine_lock = threading.Lock()


def get_engine(database_url: str | None = None):
    """Return the SQLAlchemy engine, creating it on first call.

    Uses a module-level singleton. Pass a URL to create a non-default engine.
    """
    global _engine

    if _engine is not None and database_url is None:
        return _engine

    with _engine_lock:
        # Double-check after acquiring lock
        if _engine is not None and database_url is None:
            return _engine

        if database_url is None:
            settings = load_settings()
            database_url = settings.database_url

        # Ensure data directory exists for SQLite
        if "sqlite" in database_url:
            db_path = database_url.replace("sqlite:///", "")
            Path(db_path).parent.mkdir(parents=True, exist_ok=True)

        engine = create_engine(database_url, echo=False)

        # Cache the default engine
        if _engine is None:
            _engine = engine

        return engine


def _is_empty_database(engine) -> bool:
    """True when the database holds no application tables yet."""
    tables = set(inspect(engine).get_table_names()) - {"alembic_version"}
    return not tables


def init_db(database_url: str | None = None) -> None:
    """Create or migrate all tables.

    An existing database is brought up to head with Alembic. A fresh one is
    built from SQLModel.metadata and then stamped at head, because the
    migration chain cannot build a schema from scratch: its first revision
    was autogenerated as a diff and only alters tables it assumes already
    exist. The models are the source of truth for a new database; the
    migrations exist to carry old ones forward.

    Falls back to plain create_all() when the migrations directory is absent
    (e.g. an installed package or a partial checkout).
    """
    engine = get_engine(database_url)

    # Populate SQLModel.metadata — create_all() builds only the tables that
    # have been imported, and silently does nothing if models were never
    # loaded. Imported here rather than at module scope to avoid a cycle.
    from src.storage import models  # noqa: F401

    alembic_dir = Path(__file__).parent.parent.parent / "alembic"
    if not alembic_dir.exists():
        SQLModel.metadata.create_all(engine)
        return

    from alembic.config import Config

    from alembic import command

    alembic_cfg = Config(str(alembic_dir.parent / "alembic.ini"))
    alembic_cfg.set_main_option("sqlalchemy.url", str(engine.url))
    # Leave the caller's logging alone — see alembic/env.py.
    alembic_cfg.attributes["configure_logger"] = False

    try:
        if _is_empty_database(engine):
            SQLModel.metadata.create_all(engine)
            # Stamp, don't upgrade: create_all() already built the current
            # schema, so replaying migrations would re-add existing columns.
            command.stamp(alembic_cfg, "head")
        else:
            command.upgrade(alembic_cfg, "head")
    except Exception as e:
        import logging as _logging

        _logging.getLogger(__name__).error(f"Database initialization failed: {e}")
        raise


def get_session(database_url: str | None = None) -> Session:
    """Open a new database session. Caller is responsible for closing it."""
    engine = get_engine(database_url)
    return Session(engine)


@contextmanager
def session_scope(database_url: str | None = None):
    """Context manager that yields a Session and ensures it is closed."""
    session = get_session(database_url)
    try:
        yield session
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()
